### ISSUE TITLE
suggestions in comments

### ISSUE THREAD

**Issue by Arne-Berner** [nolanderc/glasgow#1]
Setup:
NeoVim on linux
Current: 
When writing comments in a wgsl file, the lsp generates suggestions for possible keywords in wgsl
Expected:
Comments usually do not get changed by the lsp

Thank you so much for this lsp, it works way better on nvim than wgsl_analyzer. This is just a minor issue and only unexpected, not that annoying.

**Comment by nolanderc** [comment]
This is fixed in `0.3.1` on crates.io
